# Generated by Django 3.1.3 on 2020-11-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminss',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=11)),
                ('datacreate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('datacreate', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.adminss')),
            ],
        ),
        migrations.CreateModel(
            name='stus',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('datacreate', models.DateTimeField(auto_now=True)),
                ('classstu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.classes')),
            ],
        ),
    ]
