# Generated by Django 3.1.3 on 2020-11-20 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminss',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b916cd73-20ad-485d-a62f-e7cff16b8646'), primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('namesc', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5b64a1fd-44ca-4b6e-8b7a-9c50f039a16e'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.adminss')),
            ],
        ),
        migrations.CreateModel(
            name='stus',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7e5c2a4b-7ec5-4c6c-b52a-f2192d1a81ea'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('classstu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.classes')),
            ],
        ),
    ]
