# Generated by Django 3.1.3 on 2020-11-24 05:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.UUIDField(default=uuid.UUID('372f4f83-291b-4e7f-8365-a57499fab963'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68c26763-61c2-4dfb-8a58-9d89e848026b'), primary_key=True, serialize=False),
        ),
    ]
