# Generated by Django 3.1.3 on 2020-11-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stus',
            name='classstu',
        ),
        migrations.AddField(
            model_name='classes',
            name='classstu',
            field=models.ManyToManyField(to='exam.stus'),
        ),
    ]
