# Generated by Django 3.1.3 on 2020-11-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20201128_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='classstu',
        ),
        migrations.AddField(
            model_name='stus',
            name='classthisstu',
            field=models.ManyToManyField(to='exam.classes'),
        ),
    ]
