# Generated by Django 3.1.3 on 2020-11-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20201128_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='imei_admin',
            fields=[
                ('imei', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_admin', models.CharField(max_length=100)),
                ('pass_admin', models.CharField(max_length=100)),
            ],
        ),
    ]
