# Generated by Django 3.1.3 on 2020-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_imei_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminss',
            name='calsss',
            field=models.ManyToManyField(blank=True, to='exam.classes'),
        ),
        migrations.AlterField(
            model_name='stus',
            name='classthisstu',
            field=models.ManyToManyField(blank=True, to='exam.classes'),
        ),
    ]
